spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:///devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE

  r2dbc:
    url: r2dbc:h2:mem:///devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE

  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 31536000
