spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:///devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  r2dbc:
    url: r2dbc:h2:mem:///devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  resources:
    cache:
      cachecontrol:
        cache-public: true
        max-age: 31536000

  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    file: "{\"time\": \"%d\", \"level\": \"%p\", \"source\": \"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
